### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by yisibl** [yisibl/postcss-unprefix#2]
- [x] 1 Remove all prefixes? if user want to run autoprefixer, they can do it later, 1 plugin = 1 task, also they will be able to select different browsers.
- [ ]  2 I think you should use postcss-flexboxfixer and postcss-gradientfixer, becuase it is really hard part of CSS
- [ ]  3 Support hacks like in Autoprefixer. Like:
  
  ``` js
  if ( hacks[unPrefixProp] ) {
  hacks[unPrefixProp](decl)
  } else {
  decl.cloneAfter({
        prop: unPrefixProp,
        value: unPrefixValue
    })
  }
  ```
  
  There are many more difficult properties., when we can’t use just decl.prop.replace(rePrefix, ''). So we need some files for this case. File will be like:
  
  ``` js
  hack['interpolation-mode'] = function (decl) {
  decl.prop = 'image-rendering';
  }
  ```
- [x]  4 We need some code to prevent double properties. Like:
  
  ``` js
  if ( decl.parent.nodes.some( (other) => other.prop == unPrefixProp && decl.value == unPrefixValue ) ) {
  decl.removeSelf()
  }
  ```

By @ai
